#!/bin/bash


function init_docker_userid_groupid() {
    USERID=$(id -u)
    export USERID
    GROUPID=$(id -g)
    export GROUPID
}

function stop_docker_compose() {
    USERID=$(id -u)
    export USERID
    GROUPID=$(id -g)
    export GROUPID

    docker compose down
}

init_docker_userid_groupid
stop_docker_compose